// pkg/ap3-svelte/src/components/Head.svelte
<script>
</script>

<header class="">
  <div class="container">
    <span><a href="/" >[ Home ]</a>
    </span>
    <span><a href="/about" >[ About ]</a>
    </span>
    <span><a href="/page2" >[ page2 ]</a>
    </span>
    <span><a href="/page3" >[ page3 ]</a>
    </span>
    <span><a href="/page4" >[ page4 ]</a>
    </span>
  </div>
  <hr />
</header>

// react_jsr7/src/components/Head.tsx

function Page() {
  return (
  <>
    <div>
      <a href="/">Home</a>
      <a href="/about"> [ about ]</a>
      <span><a href="/task_project"> [ task_project ]</a>
      </span>
      <hr />
    </div>
  </>
  );
}
export default Page;
/*
<span><a href="/page2"> [ page2 ]</a>
</span>
*/
