// pkg/ap3-svelte/src/components/Head.svelte
<script>
</script>

<header class="">
  <div class="container">
    <span><a href="/" >[ Home ]</a>
    </span>
    <span><a href="/about" >[ About ]</a>
    </span>
    <span><a href="/page2" >[ page2 ]</a>
    </span>
    <span><a href="/page3" >[ page3 ]</a>
    </span>
    <span><a href="/page4" >[ page4 ]</a>
    </span>
  </div>
  <hr />
</header>

// pkg/ap6-preact/src/components/Head.tsx
import {Link } from 'react-router-dom';

function Page() {
  return (
  <>
    <div>
      <a href="/">Home</a>
      <a href="/about"> [ about ]</a>
      <span><a href="/page1"> [ page1 ]</a>
      </span>
      <span><a href="/page2"> [ page2 ]</a>
      </span>
      <span><a href="/page3"> [ page3 ]</a>
      </span>
      <span><a href="/page4"> [ page4 ]</a>
      </span>

      <hr />
    </div>
  </>
  );
}
export default Page;
